### PR TITLE
Create transliteration.md

### LINKED ISSUE #1664: Choose method of transliteration on slugs creation
**Is your feature request related to a problem? Please describe.**
Diacritics are converted on URL titles using, for example, "ão" to "aeo", which isn't expected to Brazilian users.

**Describe the solution you'd like**
I would like to set plain transliteration of characters. For example, "ão" to "ao".

**Teachability, Documentation, Adoption, Migration Strategy**
We could have a config override to set that.

- [x] I am capable and would like to work on implementation of this feature if it is considered.

### PR DESCRIPTION
**Pull request by robsonsobral**
Resolves [#1664](https://github.com/ExpressionEngine/ExpressionEngine/issues/1664).

## Nature of This Change

- [ ] 🐛 Fixes a bug
- [ ] 🚀 Implements a new feature
- [ ] 🛁 Rewrites existing documentation
- [ ] 💅 Fixes coding style
- [ ] 🔥 Removes unused files / code

### CODE REVIEW

**Comment by ops-andy** [comment]
@intoeetive can you confirm if this needs to go in the docs as well as thoughts on where we should put it? I think it might be good to add a section regarding creating translations anyways. thanks

**Comment by robsonsobral** [comment]
My intention with this PR is to raise the discussion.

It's something important for us who don't have English as first language.

(Let me say EECMS docs is lacking on that.)

**Comment by intoeetive** [comment]
I think we need a separate root folder / menu item "Localization". This could make the start of it

**Comment by ops-andy** [comment]
@robsonsobral per Yuri's comment, can you create a new section called "Localization" and move this page to that section then I'll merge

**Review by ops-andy — CHANGES_REQUESTED** [review]
per Yuri's comment, can you create a new section called "Localization" and move this page to that section then I'll merge

**Comment by robsonsobral** [comment]
Conflict fixed.

**Review by ops-andy — APPROVED** [review]

**Comment by ops-andy** [comment]
> Conflict fixed.

thanks!

**Pull request merged**
