### PR TITLE
Add documentation for the Filesystem class

### LINKED ISSUE #328: Documentation for the Filesystem class
The Filesystem class is widely used within ee (258 entries across 64 files) but there is not any documentation at all for it.

[ExpressionEngine/system/ee/ExpressionEngine/Library/Filesystem/](https://github.com/ExpressionEngine/ExpressionEngine/blob/6.dev/system/ee/ExpressionEngine/Library/Filesystem/Filesystem.php)

Having some documentation would be an improvement.

### PR DESCRIPTION
**Pull request by jcogs-design**
## Overview

Initial documentation for the [Filesystem](https://github.com/ExpressionEngine/ExpressionEngine/blob/6.dev/system/ee/ExpressionEngine/Library/Filesystem/Filesystem.php) class

Resolves [#328](https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/issues/328).

### CODE REVIEW

**Comment by ops-andy** [comment]
@jcogs-design This is great. thanks!
@intoeetive can you review and approve? thanks

**Comment by jcogs-design** [comment]
Having just yet again had to go spelunking in the Filesystem class for information on methods there (this time getDirectoryContents) I am wondering what more needs to happen for this documentation to be added into the Docs...

**Comment by jcogs-design** [comment]
Please bump or delete.

**Review by intoeetive — APPROVED** [review]

**Comment by ops-andy** [comment]
@jcogs-design this has been merged. Thanks for the hard work on this!

**Pull request merged**
